FinalClub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sns.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sns/urls.py
from django.urls import path
from .views import (
    SigninView, TemporaryRegistView, MainRegistView, LoginView,
    RegistCompleteView, CreateProfileView, HomeView, LogoutView,
    UserHomeView, BoardView, AccountsEditView, AccountsPasswordChangeView,
    FollowListView, FollowerListView
)
app_name = 'sns'
urlpatterns = [
    path('signin/', SigninView.as_view(), name='signin'),
    path('temporary_regist/', TemporaryRegistView.as_view(), name='temporary_regist'),
    path('main_regist/<uuid:token>', MainRegistView.as_view(), name='main_regist'),
    path('regist_complete/', RegistCompleteView.as_view(), name='regist_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('', HomeView.as_view(), name='home'),
    path('<str:host_user>/', UserHomeView.as_view(), name='user_home'),
    path('p/<str:board_id>/', BoardView.as_view(), name='board'),
    path('accounts/edit/', AccountsEditView.as_view(), name='accounts_edit'),
    path('accounts/password/change', AccountsPasswordChangeView.as_view(), name='accounts_password_change'),
    path('<str:host_user>/follow/', FollowListView.as_view(), name='follow_list'),
    path('<str:host_user>/follower/', FollowerListView.as_view(), name='follower_list'),
]

sns/models.py
from datetime import datetime, timedelta
from uuid import uuid4
import os

from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser, PermissionsMixin)
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete



# ユーザマネージャー
class UserManager(BaseUserManager):

    # 普通のアカウントを作成する際に用いられる
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('メールアドレスを入力してください')
        user = self.model(
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    # スーパーユーザのアカウントを作成する際に用いられる
    def create_superuser(self, email, password=None):
        user = self.model(
            email=email,
            password=password
        )
        user.set_password(password)
        user.is_staff = True
        user.is_active = True
        user.is_superuser = True
        user.is_admin = True
        user.save(using=self._db)
        return user


# ユーザ登録
class Users(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid4(), editable=False)
    email = models.EmailField(max_length=40, unique=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


# ユーザ登録トークンマネージャー
class UserActivateTokenManager(models.Manager):

    # ユーザをアクティベイトする処理
    def activate_user_by_token(self, token):
        user_activate_token = self.filter(
            token=token,
            expired_at__gte= datetime.now()  # 現在時刻以上のものを取り出す
        ).first()
        user = user_activate_token.user
        user.is_active = True
        user.save()
    
    def create_user_by_token(self, user):
        activate_token = self.model(
            token=uuid4(),
            expired_at= datetime.now() + timedelta(days=1),
            user=user
        )
        activate_token.save()
        print(f'http://127.0.0.1:8000/main_regist/{activate_token.token}')


# ユーザ登録トークン
class UserActivateTokens(models.Model):
    token = models.UUIDField(db_index=True)
    expired_at = models.DateTimeField(default=datetime.now() + timedelta(hours=1))
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE
    )

    objects = UserActivateTokenManager()


    class Meta:
        db_table = 'user_activate_tokens'


# # トークンの発行
# @receiver(post_save, sender=Users)
# def publish_token(sender, instance, **kwargs):
#     user_activate_token = UserActivateTokens(
#         token=str(uuid4()),
#         expired_at=datetime.now() + timedelta(days=1),
#         user=instance
#     )
#     user_activate_token.save()
#     print(f'http://127.0.0.1:8000/main_regist/{user_activate_token.token}')

# メールから学部学科を検出する
def detective_affiliation(email):
    if email == 'meijo.sns@gmail.com' or email == 'syogo1119@outlook.jp':
        return '00', '所属なし', '識別不要'
    departments = {'00': '所属なし', '01': '法', '02': '経営', '03': '経済', '04': '理工',
                   '05': '農', '07': '都市情報', '08': '人間', '09': '薬', '10': '外国語',
                   '12': '情報工'}
    courses = {'00': '識別不要', '01': '法', '11': '経営', '12': '国際経営', '21': '経済',
               '22': '産業社会', '40': '数学', '42': '電気電子工学', '43': '材料機能工学', '44': '応用化学',
               '45': '機械工学', '46': '交通機械工学', '47': 'メカトロニクス工学', '48': '社会基盤デザイン工学',
               '49': '環境創造工学', '50': '建築', '61': '生物資源', '62': '応用生物化学', '63': '生物環境科学',
               '81': '都市情報', '91': '人間', '73': '薬', '95': '国際英語', '05': '情報工学'}
    year = email[:2]
    if email[2:4] in departments:
        department = departments[email[2:4]]
    else:
        department = departments['00']
    if email[4:6] in courses:
        course = courses[email[4:6]]
    else:
        course = courses['00']
    return year, department, course


# 学生情報マネージャー
class UserAffiliationManager(models.Manager):

    def create_user_affiliation(self, user):
        year_of_admission, department, course = detective_affiliation(user.email)
        user_affiliation = UserAffiliation(
            year_of_admission=year_of_admission,
            department=department,
            course=course,
            user=user
        )
        user_affiliation.save()


# 学生情報
class UserAffiliation(models.Model):
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE       
    )
    year_of_admission = models.CharField(max_length=5)
    department = models.CharField(max_length=10)
    course = models.CharField(max_length=20)

    objects = UserAffiliationManager()

    class Meta:
        db_table = 'user_affiliation'


# # 学生情報作成
# @receiver(post_save, sender=Users)
# def create_user_affiliation(sender, instance, **kwargs):
#     user = instance
#     year_of_admission, department, course = detective_affiliation(user.email)
#     user_affiliation = UserAffiliation(
#         year_of_admission=year_of_admission,
#         department=department,
#         course=course,
#         user=instance
#     )
#     user_affiliation.save()


# プロフィールのマネージャー
class UserProfilesManager(models.Manager):

    def filter_by_profile(self, user_id):
        return self.filter(user_id=user_id).first()


# プロフィール
class UserProfiles(models.Model):
    username = models.CharField(max_length=255, unique=True)
    nickname = models.CharField(max_length=150)
    user_icon = models.ImageField(upload_to='user_icon/%Y/%m/%d/')
    user = models.OneToOneField(
        'Users', on_delete=models.CASCADE
    )
    introduction = models.TextField(null=True, blank=True, max_length=255)

    objects = UserProfilesManager()

    class Meta:
        db_table = 'profiles'


# 提示版のマネージャー
class BoardsManager(models.Manager):

    def filter_by_boards(self, user_id):
        return self.filter(user_id=user_id).all()

    def count_boards(self, user):
        return self.filter(user=user).all().count()


# 提示版
class Boards(models.Model):
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE, related_name='contributor'
    )
    user_profile = models.ForeignKey(
        'UserProfiles', on_delete=models.CASCADE, related_name='contributor_user_profile'
    )
    picture1 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture2 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture3 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture4 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture5 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture6 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture7 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture8 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture9 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    picture10 = models.ImageField(upload_to='board_pictures/%Y/%m/%d/', null=True, blank=True)
    description = models.TextField(max_length=200, null=True, blank=True)
    create_at = models.DateTimeField(default=datetime.now())
    update_at = models.DateTimeField(default=datetime.now())

    objects = BoardsManager()

    class Meta:
        db_table = 'boards'


# データが削除されたらmediaのboards_pictureが消える
@receiver(post_delete, sender=Boards)
def delete_picture(sender, instance, **kwargs):
    for i in range(1, 11):
        db_name = eval('instance.picture' + str(i))
        if db_name:
            if os.path.isfile(db_name.path):
                os.remove(db_name.path)


# 提示版いいねマネージャー
class BoardsLikesManager(models.Manager):

    def count_like(self, board):
        return self.filter(board=board).all().count()


# 提示版いいね
class BoardsLikes(models.Model):
    board = models.ForeignKey(
        'Boards', on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE
    )
    user_profile = models.ForeignKey(
        'UserProfiles', on_delete=models.CASCADE
    )

    objects = BoardsLikesManager

    class Meta:
        db_table = 'boards_likes'


# 掲示板コメント
class BoardsComments(models.Model):
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE
    )
    user_profile = models.ForeignKey(
        'UserProfiles', on_delete=models.CASCADE
    )
    board = models.ForeignKey(
        'Boards', on_delete=models.CASCADE
    )
    comment = models.TextField(max_length=100)
    create_at = models.DateTimeField(default=datetime.now())

    class Meta:
        db_table = 'boards_comments'


# follow Manager
class FollowFollowerUserManager(models.Manager):

    def count_follow(self, follow_user):
        return self.filter(follow_user=follow_user).all().count()

    def count_follower(self, follower_user):
        return self.filter(follower_user=follower_user).all().count()


# follow
class FollowFollowerUser(models.Model):
    follow_user = models.ForeignKey(
        'Users', on_delete=models.CASCADE, related_name='follow_user'
    )
    follower_user = models.ForeignKey(
        'Users', on_delete=models.CASCADE, related_name='follower_user'
    )
    create_at = models.DateTimeField(default=datetime.now())

    objects = FollowFollowerUserManager()

    class Meta:
        db_table = 'follow_follower_user'


# dm
class DMBox(models.Model):
    user = models.ForeignKey(
        'Users', on_delete=models.CASCADE, related_name='user'
    )
    partner = models.ForeignKey(
        'Users', on_delete=models.CASCADE, related_name='partner'
    )
    create_at = models.DateTimeField(default=datetime.now())

    class Meta:
        db_table = 'dm_box'


# dmの内容
class DMMessages(models.Model):
    dm_box = models.ForeignKey(
        DMBox, on_delete=models.CASCADE
    )
    message = models.TextField()

templates/sns/account_base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'sns/css/account.css' %}">
        <link rel="stylesheet" href="{% static 'sns/css/bootstrap-reboot.css' %}">
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

templates/sns/accounts_edit.html
{% extends "sns/base.html" %}
{% block title %}プロフィールを編集・{{ block.super }}{% endblock %}
{% block file%}
{% load static %}
<link rel="stylesheet" href="{% static 'sns/css/cropper.css' %}">
<link rel="stylesheet" href="{% static 'sns/css/accounts_edit.css' %}">
{% endblock %}
{% block content %}
<div class="accounts-edit-container">
    <div class="accounts-edit-wrap">
        <ul class="table-contents">
            <li class="table-item main-item">
                <a class="subject main-subject" href="{% url 'sns:accounts_edit' %}">プロフィールを編集</a>
            </li>
            <li class="table-item">
                <a class="subject" href="{% url 'sns:accounts_password_change' %}">パスワードを変更</a>
            </li>
        </ul>
        <div class="main-contents">
            {% csrf_token %}
            <div class="top-items-conteiner">
                <div class="top-items-wrap">
                    <div class="user-icon-wrap">
                        <img class="user-icon" src="{{ user_profile.user_icon.url }}">
                    </div>
                    <div class="user-icon-edit-wrap">
                        <div class="name">
                            {{ user_profile.username}}
                        </div>
                        <div class="user-icon-edit">
                            <button class="user-icon-edit-button" type="button">プロフィール写真を変更</button>
                            <input id="user-icon-input" class="none" type="file">
                        </div>
                    </div>
                </div>
            </div>
            <div class="main-items">
                <div class="label">
                    ユーザネーム
                </div>
                <div class="input-left">
                    <input id="username" placeholder="username" type="text" class="user-input" value={{ user_profile.username }}>
                    <div class="sub-text">
                    14日間はユーザ名を{{ user_profile.username }}に戻すことができません
                    </div>
                </div>
            </div>
            <div class="main-items">
                <div class="label">
                    名前
                </div>
                <div class="input-left">
                    <input id="nickname" placeholder="nickname" type="text" class="user-input" value={{ user_profile.nickname }}>
                    <div class="sub-text"></div>
                </div>
            </div>
            <div class="main-items">
                <div class="label">
                    自己紹介
                </div>
                <div class="input-left">
                    <textarea id="introduction" placeholder="introduction" type="text" class="user-input">{{ user_profile.introduction }}</textarea>
                    <div class="sub-text"></div>
                </div>
            </div>
            <div class="main-items">
                <div class="label">

                </div>
                <div class="input-left">
                    <div class="submit">
                        <button id="submit" type="button" disabled>送信する</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="workspace-container none">
    <div class='workspace-wrap'>
    <div class="workspace">
        <img id="workspace" src='' alt='' style="width: 400px; height: 400px;">
    </div>
    <div class="result">
        <button id="result-button">トリミング</button>
    </div>
    </div>
</div>
<script src="{% static 'sns/js/cropper.js' %}"></script>
<script src="{% static 'sns/js/accounts_edit.js' %}"></script>
{% endblock %}

templates/sns/accounts_password_change.html
{% extends "sns/base.html" %}
{% block title %}プロフィールを編集・{{ block.super }}{% endblock %}
{% block file%}
{% load static %}
<link rel="stylesheet" href="{% static 'sns/css/accounts_edit.css' %}">
{% endblock %}
{% block content %}
<div class="accounts-edit-container">
    <div class="accounts-edit-wrap">
        <ul class="table-contents">
            <li class="table-item">
                <a class="subject" href="{% url 'sns:accounts_edit' %}">プロフィールを編集</a>
            </li>
            <li class="table-item main-item">
                <a class="subject main-subject" href="{% url 'sns:accounts_password_change' %}">パスワードを変更</a>
            </li>
        </ul>
        <div class="main-contents">
            <div class="top-items-conteiner">
                <div class="top-items-wrap">
                    <div class="user-icon-wrap">
                        <img class="user-icon" src="{{ user_profile.user_icon.url }}">
                    </div>
                    <div class="user-icon-edit-wrap">
                        <div class="b-name">
                            {{ user_profile.username}}
                        </div>
                    </div>
                </div>
            </div>
            <form method="POST">
            {% csrf_token %}
            <div class="main-items">
                <div class="label">
                    現在のパスワード
                </div>
                <div class="input-left">
                    <input class="old-password" type="password" autocomplete="current-password" name="old_password" required id="id_old_password">
                    <div class="sub-text">
                    </div>
                </div>
            </div>
            <div class="main-items">
                <div class="label">
                    新しいパスワード
                </div>
                <div class="input-left">
                    <input class="new-password1" type="password" autocomplete="new-password" name="new_password1" required id="id_new_password1">
                    <div class="sub-text">
                    </div>
                </div>
            </div>
            <div class="main-items">
                <div class="label">
                    新しいパスワードを確認
                </div>
                <div class="input-left">
                    <input class="new-password2" type="password" autocomplete="new-password" name="new_password2" required id="id_new_password2">
                    <div class="sub-text">
                    </div>
                </div>
            </div>
            <div class="main-items">
                <div class="label">

                </div>
                <div class="input-left">
                    <div class="submit">
                        <button id="submit" type="submit" disabled>送信する</button>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'sns/js/accounts_password_change.js' %}"></script>
{% endblock %}

templates/sns/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}FS {% endblock %}</title>
    {% load static %}
    {% comment %} <link rel="stylesheet" href="{% static 'sns/css/bootstrap-reboot.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'sns/css/base.css' %}">
    <link rel="icon" href="data:,">
    {% comment %} <link rel="preconnect" href="https://fonts.googleapis.com"> {% endcomment %}
    {% comment %} <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> {% endcomment %}
    {% comment %} <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet"> {% endcomment %}
    {% block file %}
    {% endblock %}
</head>
<body>
<div class="header-wrap">
    <nav>
        <div class="header-contain">
            <div class="icon">
                <div class="icon-img">
                    <a href="{% url 'sns:home' %}"><img src="{% static 'sns/img/base/final_club.svg' %}" alt="ロゴ"></a>
                </div>
            </div>
            <div class="search">
                <div class="search-box">
                    <form action="">
                        {% csrf_token %}
                        <label for="search_input"></label><input id="search_input" type="text" placeholder="   検索">
                    </form>
                    <div id="search_box" class="box none"></div>
                    <div id="search_result" class="search-result none">
                        <div class="result-none">
                            検索結果はありません
                        </div>
                    </div>
                </div>
            </div>
            <div class="icons">
                <div class="icons-contents">
            <div class="home">
                <div class="home-icon">
                    <a href="{% url 'sns:home' %}" class="home-img"><img src="{% static 'sns/img/base/home.svg' %}" alt="ホームロゴ"></a>
                </div>
            </div>
            <div id="notice" class="notice">
                <div id="notice-icon" class="notice-icon">
                    <img id="notice-icon-img" src="{% static 'sns/img/base/notifications.svg' %}" alt="">
                </div>
                <div id="notice-box" class="notice-box none"></div>
                <div id="notice-wrap" class="notice-wrap none">
                    {% for notification in notifications %}
                        {% if notification.action_id == 1 %}
                            <div class="notice-content">
                                <div class="notice-user">
                                    <div class="user-icon">
                                        <a href="{% url 'sns:user_home' notification.action_user_profile.username %}" class="user-icon-img"><img src="{{ notification.action_user_profile.user_icon.url }}" alt=""></a>
                                    </div>
                                    <div class="user-info">
                                        <div class="user-id">
                                            <a href="{% url 'sns:user_home' notification.action_user_profile.username %}"><span class="user-id">{{ notification.action_user_profile.username }}</span></a><span class="action">があなたをフォローしました。</span><span class="date">{{ notification.day }}</span>
                                        </div>
                                    </div>
                                    <div class="can-action">
                                        <button class="can-action-contain">
                                            {% if notification.followed %}
                                                <div class="can-action-item">フォロー中</div>
                                            {% else %}
                                                <div class="can-action-item">フォローする</div>
                                            {% endif %}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        {% elif notification.action_id == 2 %}
                            <div class="notice-content">
                                <div class="notice-user">
                                    <div class="user-icon">
                                        <a href="{% url 'sns:user_home' notification.action_user_profile.username %}" class="user-icon-img"><img src="{{ notification.action_user_profile.user_icon.url }}" alt=""></a>
                                    </div>
                                    <div class="user-info">
                                        <div class="user-id">
                                            <a href="{% url 'sns:user_home' notification.action_user_profile.username %}"><span class="user-id">{{ notification.action_user_profile.username }}</span></a><span class="action">があなたの写真に「いいね！」 しました。</span><span class="date">{{ notification.day }}</span>
                                        </div>
                                    </div>
                                    <div class="can-action">
                                        <a href="{% url 'sns:board' notification.board.id %}"><img src="{{ notification.board.picture1.url }}"></a>
                                    </div>
                                </div>
                            </div>
                        {% elif notification.action_id == 3 %}
                            <div class="notice-content">
                                <div class="notice-user">
                                    <div class="user-icon">
                                        <a href="{% url 'sns:user_home' notification.action_user_profile.username %}" class="user-icon-img"><img src="{{ notification.action_user_profile.user_icon.url }}" alt=""></a>
                                    </div>
                                    <div class="user-info">
                                        <div class="user-id">
                                            <a href="{% url 'sns:user_home' notification.action_user_profile.username %}"><span class="user-id">{{ notification.action_user_profile.username }}</span></a><span class="action">があなたの写真にコメントしました:{{ notification.comment }}</span><span class="date">{{ notification.day }}</span>
                                        </div>
                                    </div>
                                    <div class="can-action">
                                        <a href="{% url 'sns:board' notification.board.id %}"><img src="{{ notification.board.picture1.url }}"></a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="room">
                <div class="room-icon">
                    <a href="" class="room-img"><img src="{% static 'sns/img/base/room.svg' %}" alt=""></a>
                </div>
            </div>
            <div class="questions">
                <div class="questions-icon">
                    <a href="" class="questions-img"><img src="{% static 'sns/img/base/question.svg' %}" alt=""></a>
                </div>
            </div>
            <div class="my-icon">
                <div id="my-icon-contain" class="my-icon-contain">
                    <img src="{% static 'sns/img/base/account_circle.svg' %}" alt="">
                </div>
                <div id="my-icon-box" class="my-icon-box none"></div>
                <div id="my-icon-description" class="my-icon-description none">
                    <div class="profile-wrap">
                        <div class="profile-content">
                            <div class="profile-icon">
                                <img src="{% static 'sns/img/base/account_circle.svg' %}" alt="">
                            </div>
                            <div class="profile-text">
                                <a class="a" href="{% url 'sns:user_home' username %}">プロフィールへ</a>
                            </div>
                        </div>
                    </div>
                    <div class="settings-wrap">
                        <div class="setting-content">
                            <div class="setting-icon">
                                <img src="{% static 'sns/img/base/settings.svg' %}" alt="">
                            </div>
                            <div class="setting-text">
                                <a class="a" href="{% url 'sns:accounts_edit' %}">設定へ</a>
                            </div>
                        </div>
                    </div>
                    <hr class="line">
                    <div class="logout-wrap">
                        <div class="logout-content">
                            <a href="{% url 'sns:logout' %}" class="logout">ログアウト</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            </div>
        </div>
    </nav>
</div>
{% block content %}
{% endblock %}
<script src="{% static 'sns/js/jquery-3.6.0.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'sns/js/base.js' %}" ></script>
{% comment %} <script src="{% static 'sns/js/async.js' %}"></script> {% endcomment %}
</body>
</html>

templates/sns/regist_complete.html
{% extends "sns/account_base.html" %}
{% block title %}FC 本登録完了{% endblock %}
{% block content %}
<div class="container">
    <div class="wrap">
        <div class="logo-container">
            <div class="logo">
                FINAL CLUB
            </div>
        </div>
        <div class="form-container">
            <h2>FINAL CLUBにようこそ！！！</h2>
            <hr>
            <div class="temporary">
                <a href="{% url 'sns:login' %}">ログイン画面へ</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/sns/temporary_regist.html
<h1>仮登録完了しました。</h1>

templates/sns/user_home.html
{% extends "sns/base.html" %}
{% block title %}{{ block.super }}{{ host_user.username}}{% endblock %}
{% block file%}
{% load static %}
<link rel="stylesheet" href="{% static 'sns/css/user_home.css' %}">
{% endblock %}
{% block content %}
<div class="user-home-container">
    <div class="user-home-wrap">
        <div class="profile-wrap">
            <div class="profile-image">
                <img src="{{ host_user.user_icon.url }}" alt="">
            </div>
            <div class="profile-description">
                <div class="profile-description-wrap">
                <div class="top">
                    {% csrf_token %}
                    <div class="username">
                        <h2 class="username-text">{{ host_user.username }}</h2>
                    </div>
                    <div class="action-message">メッセージを送信</div>
                    {% if  follow == "self" %}
                    <div class="follow-action profile-update"><a class="" href="{% url 'sns:accounts_edit' %}">プロフィール更新</a></div>
                    {% elif follow == "followed" %}
                    <div class="follow-action clear-follow" data-username={{host_user.username}}>フォローを解除</div>
                    {% else %}
                    <div class="follow-action follow" data-username={{host_user.username}}>フォローをする</div>
                    {% endif %}
                    <div class="setting"><img src="{% static 'sns/img/home/three_point.svg' %}" alt=""></div>
                </div>
                <div class="middle">
                    <div class="board-count">投稿<span class="strong">{{ number_of_board }}</span>件</div>
                    <a href="{% url 'sns:follower_list' host_user.username %}"><div class="follower-count">フォロワー<span class="strong">{{ count_follower}}</span>人</div></a>
                    <a href="{% url 'sns:follow_list' host_user.username %}"><div class="follow-count">フォロー<span class="strong">{{ count_follow }}</span>人</div></a>
                </div>
                <div class="bottom">
                    <div class="nickname">{{ host_user.nickname }}</div>
                    <div class="user-intro">{{ host_user.introduction }}</div>
                </div>
                </div>
            </div>
        </div>
        <div class="boards-container">
            <div class="boards-wrap">
                {% for board in boards %}
                <div class="board"><a href="{% url 'sns:board' board.id %}"><img src="{{ board.picture1.url}}" alt=""></a></div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<script src="{% static 'sns/js/user_home.js' %}"></script>
{% endblock %}